### PR TITLE
easy one line setup

### PR DESCRIPTION
**Pull request by wilkerlucio**
Hi,

Chef made major part of process really easy, but I mean all that setup code can just be easy fetching a shell script and running it on one line.

So, I just moved the shell code into a file and changed README to one line fetch and run file.

### CODE REVIEW

**Comment by wilkerlucio** [comment]
The pull request has 4 commits :)

It's on the first one.

**Comment by wilkerlucio** [comment]
Even without error handling user can see the output, I mean it will not be hard to see where it happened, and I mean most of time they will no happen at all (only when he got some network issue). But I will try to make some Ruby script (Im better on that :)) to make the setup more reliable on bad situations.

**Comment by wilkerlucio** [comment]
Oh, sorry, I need to try to do it on sh, since clean system don't have Ruby

**Comment by wilkerlucio** [comment]
But at all, I mean the user has best chance on getting more errors if he tries to type that all (and type wrong) than with the script, hehe.

I can try to make the shell more bullet prof, but will take some time to realize how I do it, hehe

**Comment by rosenfeld** [comment]
Yes, I know, and that is why I didn't do it myself ;) But I don't think someone will type all that script but copy and paste instead. At least this is what I do when I install Gitorious using those instructions.

But go ahead, if you could take care of, at least, stop processing when some error happens in any of the commands we can push the scripts alongside with instructions. Also the script should be able to restart from where it stopped without problems.

Anyway, I would like to keep the original instructions in the README as well so the user can choose which option to use. You could write something like:

"There are two procedures for installing Gitorious. This is a one-liner command that will run the instructions provided in the Detailed Instructions section: ..."

**Comment by wilkerlucio** [comment]
Ok, I when I got some free time I will take the adventure :)

But about the paste, how you paste it? I'm doing the trials on VMWare Fusion here, I can't paste on a system with just terminal... And I mean it can get even worst if the person is doing it on a dedicated machine (I will need to do that this week, hehe).

Paste I mean can works if you have ssh access, but for dedicated machines it's much more complicated, hehe.

**Comment by rosenfeld** [comment]
I always enable SSH and it is required for Gitorious push to work. So why is it more complicate for dedicated machines?

**Comment by wilkerlucio** [comment]
At least here, the SSH access don't came by default... So I need to setup it before, but anyway, I really need to setup SSH at some point, but I really like the ideia to install OS, run 1 line for setup, config node.json, run one more command and have all up and running :)

I will try to make the sh script work in just one step (in the process, open Vim with node.json, so, user configure, save, quit, and them sh automatic continue to chef gitorious setup)

**Comment by rosenfeld** [comment]
The problem with that approach is that although we are familiar with Vim, those who don't use it (some prefer nano for instance) won't know how to edit the file for instance.

**Pull request closed without merging**
