### PR TITLE
Deal with failure when git-daemon fails to start due to bundle failing it

### PR DESCRIPTION
**Pull request by drt24**
For some reason which bundles are visible depends on which user is running things even if the install is done as root and so it may be necessary to do bundle install as the git user as well. Oh for a proper package management system like apt-get.

### CODE REVIEW

**Comment by rosenfeld** [comment]
Thank you, Daniel. Could you please create a Troubleshooting section in the Wiki instead and document it there.

This seems to be Ubuntu specific since I never could replicate this in the Debian boxes I've tried this recipe. For example, Debian doesn't have sudo installed by default.

So I'd prefer to have just a link in the README pointing to the Wiki Troubleshooting section. Could you please do that?

**Comment by rosenfeld** [comment]
Also, there is no need to "cd" to the "script" directory. The instructions should be changed to

```
cd /var/www/gitorious
```

**Comment by drt24** [comment]
Ok I will make a wiki section

**Comment by drt24** [comment]
Wiki section made. Do you want to link it off the README.md?

**Comment by rosenfeld** [comment]
Thank you, I've just linked your Troubleshooting page in the Home page.

It would be great to reference it in the README as well. Thanks :)

**Comment by rosenfeld** [comment]
I was reading your Troubleshooting page and I couldn't understand some parts. I've simplified the "bundle install" procedure too.

I didn't get what you mean by having postgresql already installed in the system. Gitorious uses MySQL, so it shouldn't matter. Anyway, I should also state that this recipe was only tested against a fresh Debian basic install and there could be some issues if MySQL was previously installed already.

I think I'll add those notes to the wiki pages as well.

**Pull request closed without merging**
